manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos/zephyr
  projects:
    - name: zephyr
    - remote: zephyrproject
  self:
    path: net_ieee802154_radio_build_fail
